name: symbiflow-env
channels:
  - defaults
  - litex-hub
dependencies:
  - litex-hub::yosys-uhdm=0.5_8401_g30b87e190
  - python=3.7
  - pip
  - pip:
    - -r ../common/requirements.txt
    - -r requirements.txt
