name: nextpnr-env
channels:
  - defaults
  - litex-hub
dependencies:
  - litex-hub::yosys=0.9_5457_gc6681508=20210615_141355_py38
  - litex-hub::vtr-optimized=8.0.0_3614_gb3b34e77a=20210507_125510
  - litex-hub::nextpnr-fpga_interchange=v0.0_3686_g034467ff=20210625_074838
  - litex-hub::nextpnr-ice40=0.0.0_2726_g1afa494=20201126_123829
  - litex-hub::nextpnr-xilinx=v0.0_2818_ge69bbf9e=20210415_092356
  - litex-hub::prjxray-db=0.0_252_g8372b58=20210622_220029
  - litex-hub::prjxray-tools=0.1_2842_g6867429c=20210301_104249
  - litex-hub::capnproto=0.8.0=20210316_201220
  - litex-hub::capnproto-java=0.1.5_18_gcf62cd4=20210316_201220
  # swig is required to build the rapidyaml package
  # It can be removed once that is available in PyPi
  - swig
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:../common/requirements.txt
    - -r file:requirements.txt
