name: Generate results page

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

jobs:
  generate-results-page:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Make environment
        run: |
          python3 -m pip install virtualenv
          cd results
          make env

      - name: Build HTML
        run: |
          cd results
          make fetch
          make build

      - uses: actions/upload-artifact@v2
        with:
          name: html-results
          path: results/build/*

      - name: Deploy to GH pages
        if: ${{ (github.event_name == 'push' || github.event_name == 'schedule') &&
                github.ref == 'refs/heads/master' }}
        run: |
          cd results/build
          git init
          cp ../../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha  }}"
          git push -u origin +HEAD:gh-pages

